### ISSUE TITLE
어떤 피쳐가 가장 좋을까?

### ISSUE THREAD

**Issue by byeongal** [kookmin-sw/2018-cap1-16#1]
정적 분석(peframe, ida pro)과 동적 분석(cuckoosandbox)결과로 나오는 자료중 어떠한 피쳐를 사용하는게 가장 좋을까?

**Comment by byeongal** [comment]
정적 분석을 할때는 가장 기초적으로는 바이러스 토탈, 해시, 파일의 문자열, 함수, 헤더를 보고 분석 한다.

**Comment by byeongal** [comment]
https://media.kaspersky.com/en/enterprise-security/Kaspersky-Lab-Whitepaper-Machine-Learning.pdf

카스퍼스키에서도 해당 내용을 연구하고 있음

**Comment by cyhan1004** [comment]
고동우, 김휘강(2017) "API 콜 시퀀스와 Locality Sensitive Hashing을 이용한 악성코드 클러스터링 기법에 관한 연구", 정보보호학회논문지
동적분석 리포트 결과로 API 콜 시퀀스를 파싱할 수 있는데, 동일한 기능을 수행하는 함수를 상이한 함수로 잘못 식별하는 문제점이 있어서 cuckoo sandbox에서 자체적으로 정의한 기준에 따라 323개의 함수들을 카테고리로 묶은 방법을 이용함

**Comment by cyhan1004** [comment]
최보민, 강홍구, 이태진(2016) "동적분석 기반 악성코드 자동 분류 기법에 관한 연구", 한국인터넷진흥원
위의 논문에서는 API 호출 순서/빈도/조합을 사용함

결론 : API call sequence(+category)가 동적분석 피쳐에서 핵심으로 사용되는 것을 확인함.

**Comment by byeongal** [comment]
피쳐 및 모델 검증을 위한 토이 셋 제작 완료
악성 : 바이러스 사인에서 다운로드 받은 8월 2일부터 12일까지 데이터중 32bit pe파일 10,000개
정상 : 크롤링한 정상 파일중 32bit pe파일 10,000개

**Comment by Brilliantw** [comment]
Igor Santos 외 6명(2010) "Idea: Opcode-sequence-based Malware Detection"에서 opcode sequence를 이용하여 변종 악성코드를 탐지할 수 있음을 보임.

**Comment by Brilliantw** [comment]
I. Santos 외 2명(2011) "Using opcode sequences in single-class learning to detect unknown malware", IET Information Security
위의 논문에서는 머신러닝을 이용한 악성코드 탐지에서 opcode sequence를 학습시켰을 때 높은 정확도로 악성코드 탐지가 가능함을 보임

**Comment by Brilliantw** [comment]
Asaf Shabtai 외 4명 "Detecting unknown malicious code by applying classification techniques on OpCode patterns", Security Informatics
위의 논문에서는 opcode n-gram을 이용하여 알려지지 않은 악성코드를 높은 정확도로 탐지해냄.

결론 : 정적분석 피처에서 opcode sequence가 높은 성능을 보이는 것을 확인함.

**Comment by Brilliantw** [comment]
Xin Hu 외 3명(2013) "MutantX-S: Scalable Malware Clustering Based on Static Features", 2013 USENIX
Annual Technical Conference '

위 논문에서는 정적 피처로 Control-flow graph, binary sequence, mnemonic sequence와 같은 피처 대신 opcode sequence를 사용하는게 더 좋다고 주장함.

**Comment by byeongal** [comment]
결론
* 정적 : opcode sequence
* 동적 : API call sequence
를 사용 하는 것이 좋다.
