### ISSUE TITLE
정상 파일 크롤링 하기

### ISSUE THREAD

**Issue by byeongal** [kookmin-sw/2018-cap1-16#10]
신뢰할 수 있는 개발사에서 개발한 프로그램을 정상파일이라고 가정하고 정상 파일 모으기

**Comment by Junnyung-Heo** [comment]
윈도우 내장 프로그램은 신뢰할 수 있는 정상파일이므로 
윈도우 vista 32,64 bit clean버전을 각각 구했음

**Comment by yoojeong96** [comment]
Windows 8.1 32, 64 bit clean 버전을 각각 구함

**Comment by byeongal** [comment]
윈도우 10 32bit, 64bit 확보

**Comment by cyhan1004** [comment]
윈도우 7 얼티밋 K버전 32bit, 64bit 확보

**Comment by Junnyung-Heo** [comment]
정상 피일 크롤링을 위해 설치된 프로그램 목록

Microsoft Windows 10 Enterprise build 16299

Adobe Acrobat Reader DC
Adobe Photoshop CS 6
Android SDK Tools
Battle.net
Chrome
Cocos Creator
Crazy Arcade
Epic Games Launcher
Git version 2.16.1.4
IIS 10.0 Express
Intel Hardware Acceleated Execution Manager
Java 10
Java SE Development Kit 8 update 161
Java(TM) SE Development Kit 10
JetBrains PyCharm 2017.3.4
MapleStory
Microsoft .Net Core SDK - 2.1.102
League of Legends
Microsoft Azure Authorizing Tools - v2.9.5.3
Microsoft Azure compute Emulator - v2.9.5.3
Microsoft Azure Libraries for .NET -2.9
Microsoft Azure Mobile App SDK -v3.0
Microsoft Azure PowerShell -December 2017
Microsoft Azure Storage Emulator-v5.4
Microsoft Azure Storage Tools -v6.2.0
Microsoft Emulator - Windows 10.0.15254.1
Microsoft Help Viewer 2.3
Microsoft Identity Extensions
Microsoft MPI(7.1.12437.25)
Microsoft Office Professional Plus 2016
Microsoft OneDrive
Microsoft R Client
Microsoft SQL Server 2012 Native Client
Microsoft SQL Server 2016 LocalDB
Microsoft Visual C++ 2008 Redistribute -x64 9.0.30729.4148
Microsoft Visual C++ 2008 Redistribute -x86 9.0.30729.4148
Microsoft Visual C++ 2010 x64 Redistribute - 10.0.40219
Microsoft Visual C++ 2010 x86 Redistribute - 10.0.40219
Microsoft Visual C++ 2012 Redistribute(x64) - 11.0.61030
Microsoft Visual C++ 2012 Redistribute(x86) - 11.0.61030
Microsoft Visual C++ 2013 Redistribute(x64) - 12.0.30501
Microsoft Visual C++ 2013 Redistribute(x64) - 12.0.40660
Microsoft Visual C++ 2013 Redistribute(x86) - 12.0.30501
Microsoft Visual C++ 2013 Redistribute(x86) - 12.0.40660
Microsoft Visual C++ 2017 Redistribute(x64) - 14.10.25017
Microsoft Visual C++ 2017 Redistribute(x86) - 14.10.25017
Microsoft Visual Studio 2010 Tools for Office Runtime (x64)
Microsoft Visual Studio 2010 Tools for Office Runtime(x64) 언어 팩 - 한국어
Microsoft Visual Studio Installer
Microsoft Web Deploy 4.0
Microsoft XNA Framework Redistribute 4.0
Microsoft 도움말 뷰어 2.3 언어 팩 - 한국어
NeoplePlugin
Nexon Game Manager
NVIDIA PhysX 시스템 소프트웨어 9.17.0524
OpenAL
PLAYERUNKNOWN'S BATTLEGROUNDS
Python 2.7.13(Anaconda2 5.0.0 32-bit)
Python 2.7.13(Anaconda2 5.0.0 64-bit)
Python 2.7.14
Python 2.7.14(64-bit)
Python 3.6.2(Anaconda2 5.0.0 32-bit)
Python 3.6.2(Anaconda2 5.0.0 64-bit)
Python 3.6.3(64-bit)
Python 3.6.4(32-bit)
Python Launcher
Realtek High Definition Audio Driver
Skype™ 7.40
SQL Server 2017용 Microsoft System CLR Types
Steam
Unity
Visual Studio Enterprise 2017
Vulkan Run Time Libraries 1.0.26.0
Windows 10 for Mobile Image - 10.0.15254.0
Windows 10 업데이트 도우미
Windows SDK AddOn
Windows Setup Remediations (x64) (KB4023057)
Windows Software Development Kit - Windows 10.0.10586.212
Windows Software Development Kit - Windows 10.0.14393.795
Windows Software Development Kit - Windows 10.0.15063.674
Windows Software Development Kit - Windows 10.0.16299.15
Windows Software Development Kit - Windows 10.0.26624
Xcreax IncrediBuild 9.2.1 (build 2173)
디아블로 Ⅲ
스타크래프트
스타크래프트 Ⅱ
오버워치
월드 오브 워크래프트
카카오톡
카트라이더
하스스톤 

위 프로그램으로 부터 추출된 exe,dl(32,64bit) 파일의  총 개수 57,117개

**Comment by Brilliantw** [comment]
윈도우 XP 32bit, 64bit 확보

**Comment by Brilliantw** [comment]
Microsoft Windows 10 Enterprise build 16299 64bit
Microsoft Windwos 10 Education build 16299 32bit
Microsoft Windwos 7 Home Premium K build 7601 64bit
Microsoft Windwos 7 Home Premium K build 7601 32bit

Adobe Acrobat DC
Adobe Acrobat Reader DC
Adobe After Effects CC
Adobe Animate CC
Adobe Audition CC
Adobe Bridge CC
Adobe Character Animator CC
Adobe Creative Cloud 4.4.1.298
Adobe Dimension CC
Adobe Dreamweaver CC
Adobe Fuse CC(Beta)
Adobe Illustrator CC
Adobe InCopy CC
Adobe InDesign CC
Adobe Lightroom CC
Adobe Lightroom Classic CC
Adobe Media Encoder CC
Adobe Muse CC
Adobe Prelude CC
Adobe Premiere Pro CC
Adobe Photoshop CS 6
Adobe XD CC
Ahnlab V3 Internet Security 9.0
Android SDK Tools
Avast Free Antivirus 18
AVG Protection Free 2016
Avira Antivirus 15
Avira Launcher 1
Battle.net
Bitdefender Agent 22
Bitdefender Antivirus (버전 미상)
BullGuard Premium Protection 18.0
Chrome
Cocos Creator
COMODO Internet Security Premium 10
Crazy Arcade
Epic Games Launcher
eScan Anti-Virus (AV) Edition for Windows 14
F-Secure AntiVirus 3
G DATA INTERNET SECURITY 25
G DATA TOTAL SECURITY 25
Git version 2.16.1.4
IIS 10.0 Express
Intel Hardware Acceleated Execution Manager
Java 10
Java SE Development Kit 8 update 161
Java(TM) SE Development Kit 10
JetBrains PyCharm 2017.3.4
K7TotalSecurity 15.00
Kaspersky Internet Security 18.0.0.405 
MapleStory
MapleStory 2
McAfee WebAdvisor 4
McAfee® 토탈 프로텍션 16.0 R7
Microsoft .Net Core SDK - 2.1.102
League of Legends
Microsoft Azure Authorizing Tools - v2.9.5.3
Microsoft Azure compute Emulator - v2.9.5.3
Microsoft Azure Libraries for .NET -2.9
Microsoft Azure Mobile App SDK -v3.0
Microsoft Azure PowerShell -December 2017
Microsoft Azure Storage Emulator-v5.4
Microsoft Azure Storage Tools -v6.2.0
Microsoft Emulator - Windows 10.0.15254.1
Microsoft Help Viewer 2.3
Microsoft Identity Extensions
Microsoft MPI(7.1.12437.25)
Microsoft Office Professional Plus 2016
Microsoft OneDrive
Microsoft R Client
Microsoft SQL Server 2012 Native Client
Microsoft SQL Server 2016 LocalDB
Microsoft Visual C++ 2008 Redistribute -x64 9.0.30729.4148
Microsoft Visual C++ 2008 Redistribute -x86 9.0.30729.4148
Microsoft Visual C++ 2010 x64 Redistribute - 10.0.40219
Microsoft Visual C++ 2010 x86 Redistribute - 10.0.40219
Microsoft Visual C++ 2012 Redistribute(x64) - 11.0.61030
Microsoft Visual C++ 2012 Redistribute(x86) - 11.0.61030
Microsoft Visual C++ 2013 Redistribute(x64) - 12.0.30501
Microsoft Visual C++ 2013 Redistribute(x64) - 12.0.40660
Microsoft Visual C++ 2013 Redistribute(x86) - 12.0.30501
Microsoft Visual C++ 2013 Redistribute(x86) - 12.0.40660
Microsoft Visual C++ 2017 Redistribute(x64) - 14.10.25017
Microsoft Visual C++ 2017 Redistribute(x86) - 14.10.25017
Microsoft Visual Studio 2010 Tools for Office Runtime (x64)
Microsoft Visual Studio 2010 Tools for Office Runtime(x64) 언어 팩 - 한국어
Microsoft Visual Studio Installer
Microsoft Web Deploy 4.0
Microsoft XNA Framework Redistribute 4.0
Microsoft 도움말 뷰어 2.3 언어 팩 - 한국어
NeoplePlugin
Nexon Game Manager
Norton Security 22
NVIDIA PhysX 시스템 소프트웨어 9.17.0524
OpenAL
PC Matic 3
PC Pitstop Info Center 1
PLAYERUNKNOWN'S BATTLEGROUNDS
Python 2.7.13(Anaconda2 5.0.0 32-bit)
Python 2.7.13(Anaconda2 5.0.0 64-bit)
Python 2.7.14
Python 2.7.14(64-bit)
Python 3.6.2(Anaconda2 5.0.0 32-bit)
Python 3.6.2(Anaconda2 5.0.0 64-bit)
Python 3.6.3(64-bit)
Python 3.6.4(32-bit)
Python Launcher
Realtek High Definition Audio Driver
Skype™ 7.40
SQL Server 2017용 Microsoft System CLR Types
Steam
Unity
VIPRE Advanced Security 10
Visual Studio Enterprise 2017
Vulkan Run Time Libraries 1.0.26.0
Windows 10 for Mobile Image - 10.0.15254.0
Windows 10 업데이트 도우미
Windows SDK AddOn
Windows Setup Remediations (x64) (KB4023057)
Windows Software Development Kit - Windows 10.0.10586.212
Windows Software Development Kit - Windows 10.0.14393.795
Windows Software Development Kit - Windows 10.0.15063.674
Windows Software Development Kit - Windows 10.0.16299.15
Windows Software Development Kit - Windows 10.0.26624
Xcreax IncrediBuild 9.2.1 (build 2173)

던전앤파이터
드래곤네스트
디아블로 Ⅲ
로스트사가
마비노기
마비노기영웅전
바람의나라
버블파이터
싸이퍼즈
서든어택
스타크래프트
스타크래프트 Ⅱ
아르피엘
아스가르드
아키에이지
어둠의전설
엘소드
오버워치
이카루스
일렌시아
월드 오브 워크래프트
천애명월도
카오스 온라인
카운터 스트라이크 온라인
카운터 스트라이크 온라인 2
카카오톡
카트라이더
크리티카
클로져스
탱고파이브
테라
테일즈위버
트리오브세이비어
파이널판타지XIV
프리스타일2
피파온라인3
하스스톤
하이퍼유니버스
한컴오피스 2018 한글

위 프로그램들로부터 추출된 exe,dll(32,64bit) 파일의 총 개수 87,489개
