### ISSUE TITLE
악성코드 샘플 파일 빅 데이타 처리 이슈

### ISSUE THREAD

**Issue by Brilliantw** [kookmin-sw/2018-cap1-16#12]

**Comment by Brilliantw** [comment]
http://wildpup.cafe24.com/archives/929 
이 링크를 참고하여 ec2 인스턴스를 원격으로 다루는데 필요한 access key와 secret key를 얻어낼 수 있다.

**Comment by Brilliantw** [comment]
원격 세션 만든 후 session token 가져오기

Download and install the Amazon Command Line Interface
http://docs.aws.amazon.com/cli/latest/userguide/installing.html
Configure the command line interface
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
$aws configure
Request the session token
$aws sts get-session-token --duration-seconds 129600 (enter your own duration)

**Comment by Junnyung-Heo** [comment]
현재 확보된 600만개의 악성코드 샘플에 대하여 상담 받은 결과
실시간 서비스중에 read write 중 read 연산을 주로 하게 되므로
현재 운용중인 mongoDB로 단일 서버 구성은 문제가 없을 것 이라는 결론을 얻음
