### ISSUE TITLE
Cuckoo Sandbox와 Elasticsearch 연동 문제

### ISSUE THREAD

**Issue by cyhan1004** [kookmin-sw/2018-cap1-16#27]
쿠쿠샌드박스와 엘라스틱서치 연동 설정 하였으나, 연동 실패
연동 에러 : "Could not convert [procmemory.include_in_root] to boolean"

**Comment by cyhan1004** [comment]
현재 쿠쿠샌드박스와 엘라스틱서치 연동하기 위해서는 엘라스틱서치 버전 5.x까지만 가능함(6.x부터 지원 안 함)

**Comment by Junnyung-Heo** [comment]
5.5 설치후 연동에 성공함
