### ISSUE TITLE
악성코드를 어떻게 분류할까?

### ISSUE THREAD

**Issue by Junnyung-Heo** [kookmin-sw/2018-cap1-16#8]
악성코드에게 어떠한 기준으로 라벨을 부여해 분류할 것인가?

**Comment by byeongal** [comment]
https://usa.kaspersky.com/resource-center/threats/types-of-malware

**Comment by byeongal** [comment]
https://www.kaspersky.com/blog/a-malware-classification/3037/

**Comment by byeongal** [comment]
카스퍼스키 라벨을 참고해서 7개의 라벨로 분류
